created CONTRIBUTING.md and CONTRIBUTING_JP.md
haruki7049/hrtor pull request #48
Opened 2023-12-04 04:42 UTC by haruki7049

close #45

2023-12-06 12:16 UTC, AsPulse requested changes
CI/CDが通ってることを確認してから……とあるんですが、RulesetでCI/CD通過を必須条件にして、`CONTRIBUTING.md`からは記述削除でいいと思います！

2023-12-06 13:09 UTC, haruki7049 commented
御意。理解した。でも今Rulesetsの設定を見たらCIの方は設定が無くて、CDならあったんだよね。継続的デプロイをした方が良いのかなぁ…？

2023-12-06 13:11 UTC, AsPulse commented
いや、CIの方もあるはずですよ
Require pass status checks... みたいな文言だったはず

2023-12-06 13:24 UTC, haruki7049 commented
あった。からちょっと試してる

2023-12-09 04:04 UTC, AsPulse commented on .github/CONTRIBUTING_JP.md
> +- `Create a merge commit`でマージしてください。
これ、そもそも`Create a merge commit`しか出来ないようにRepositoryの設定ができるので、そうすることをオススメします

2023-12-09 04:07 UTC, AsPulse submitted a review, later dismissed
LGTM! (設定だけ変えておいてください)

2023-12-09 04:12 UTC, AsPulse approved these changes

2023-12-09 04:12 UTC, merged